### ISSUE TITLE
Importing datatypes, user etc. does not work if done before setting the API_ROOT

### ISSUE THREAD

**Issue by swapnilgt** [dgrtwo/ParsePy#137]
I have written a python script for my self hosted parse-server and I am using a function written as a part of my cloud code. The problem is that if I import the datatypes (`from parse_rest.datatypes import Function` in my case) before setting the API_ROOT:

`parse_rest.connection.API_ROOT = 'my.api.url'`

I get the following exception:

`parse_rest.core.ResourceRequestLoginRequired: {"error":"unauthorized"}`

The modules seem to be initialized with an existing api url (maybe the default parse.com url). Is this a known issue?

**Comment by milesrichardson** [comment]
I submitted PR #138 to fix this

**Comment by danrobinson** [comment]
Fixed by #138
