### ISSUE TITLE
config/global.json

### ISSUE THREAD

**Issue by michaelPhelps** [dgrtwo/ParsePy#83]
After installing the command line tools and setting up the cloud code as dictated here : https://www.parse.com/docs/cloud_code_guide

I keep getting this error: 
E..................................
======================================================================
ERROR: test_simple_functions (__main__.TestFunction)
test hello world and averageStars functions
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/parse_rest/tests.py", line 394, in setUp
    with open("config/global.json", "w") as outf:
IOError: [Errno 2] No such file or directory: 'config/global.json'

----------------------------------------------------------------------
Ran 35 tests in 37.125s

FAILED (errors=1)

The directory I am trying to run "python -m 'parse_rest.tests' looks like this:
cloud              config             public             settings_local.py  settings_local.pyc

**Comment by mclean25** [comment]
I keep getting the same issue

**Comment by bradddd** [comment]
Go to the directory where cloudcode is installed, or look in the test.py file to see the directory that it changes to right before the open() call fails. You're probably missing the config directory. Just create a directory there named "config" to get the test to work.

**Comment by dankrause** [comment]
Fixed by dd38bb027de56d4f083a71226971dbfb4e511efa
