### ISSUE TITLE
How to create an arbitrary Object with dynamic Parse Class name

### ISSUE THREAD

**Issue by bitfinity** [dgrtwo/ParsePy#94]
I want to be able to create an arbitrary object as follows.  Is this possible with your library?

````
flingyClass = 'Flingy' if something else 'FlingySomethingElse'
flingy = Object(className=flingyClass)
# and be able to query
flingy.Query.all()
````

**Comment by dgrtwo** [comment]
Yes, using the `Object.factory` method:

    from parse_rest.datatypes import Object

    flingyClass = "FlingySomethingElse"
    flingy = Object.factory(flingyClass)

    print flingy
    # <class 'parse_rest.datatypes.FlingySomethingElse'>
    print flingy.__name__
    # FlingySomethingElse

You'll be able to use Query etc from that point on. You can see the code for that method [here](https://github.com/dgrtwo/ParsePy/blob/master/parse_rest/datatypes.py#L413).

**Comment by bitfinity** [comment]
Awesome thanks!
