### ISSUE TITLE
Unable to import ACL class

### ISSUE THREAD

**Issue by flound1129** [dgrtwo/ParsePy#96]
When I try to import the ACL class as described in the doc, I get the following error:

ImportError: cannot import name ACL

**Comment by mcastle** [comment]
Can you please post/link the full console log. Thanks.

**Comment by flound1129** [comment]
$ ./fix_Question.py 
Traceback (most recent call last):
  File "./fix_Question.py", line 5, in <module>
    from parse_rest.datatypes import ACL
ImportError: cannot import name ACL

**Comment by flound1129** [comment]
Full script:

#!/usr/bin/python
from parse_rest.connection import register
register(...)
from parse_rest.datatypes import Object
from parse_rest.datatypes import ACL
from parse_rest.user import User


class Answer(Object):
    pass

skip=0
done=False

while done == False:
    answers = Answer.Query.filter(parent__exists=False).limit(1000).skip(skip)

    if len(answers) > 1000:
        done = True
    else:
        skip += 1000

    for answer in answers:
        print "id was %s" % answer.objectId
        asker = answer.askedof
        user = User();
        user.objectId = asker
        answer.parent = answer.autoquestionid
        answer.User = user;
        answer.ACL.set_user(user, read=True, write=True)
        answer.ACL.set_default(read=True)
        answer.ACL.set_role('admin', read=True, write=True)
        answer.save();

**Comment by mcastle** [comment]
Can you please confirm that you're using the most recent version of parse_rest, which includes the ACL class in parse_rest.datatypes?

**Comment by flound1129** [comment]
Yes you are correct, I had the latest version cloned but I had forgotten to install it.  Sorry for the trouble.
